### ISSUE TITLE
在 k8s 上 pod cpu 满载

### ISSUE THREAD

**Issue by chunlongyuan** [Allenxuxu/gev#70]
### 一、问题描述

我在两套 k8s 环境都有出现，我分配多少CPU他运行一辆天后就占用多少CPU。在没有什么用户量的情况下就会出现占满。

1、运行环境 
```
# 运行系统
alpine:3.11
# gev 版本
github.com/Allenxuxu/gev v0.1.9
# golang 版本
golang:1.15

```

2、部分编排文件
```
        livenessProbe:
          tcpSocket:
            port: 6061
          periodSeconds: 3
          initialDelaySeconds: 3
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 1
            memory: 2Gi
```

3、没有新的连接，仅有一些连接和断开的日志，基本都是这种日志，大概隔几秒会有一组
```
[server_gev_handler.go:25::dm-im/im-gateway/server.(*gevHandler).OnConnect()] Mar 16 09:34:38.953 [D] OnConnect remote address is 172.31.19.178:11738
[server_gev_handler.go:25::dm-im/im-gateway/server.(*gevHandler).OnConnect()] Mar 16 09:34:38.954 [D] OnConnect remote address is 172.31.28.106:46826
[server_gev_handler.go:156::dm-im/im-gateway/server.(*gevHandler).OnClose()] Mar 16 09:34:38.954 [D] OnClose remote address is 172.31.19.178:11738
[server_gev_handler.go:156::dm-im/im-gateway/server.(*gevHandler).OnClose()] Mar 16 09:34:38.954 [D] OnClose remote address is 172.31.28.106:46826
```

4、pod CPU 信息（当前分配1000M，测试了分配2000M也会满）
```
im-gateway-857f97b9f-ld2kt             993m         16Mi
```

5、连接占满的情况下的连接信息
```
/data # netstat -nat |awk '{print $6}'|sort|uniq -c|sort -rn
     19 ESTABLISHED
      8 CLOSE_WAIT
      4 LISTEN
      1 established)
      1 Foreign
```

6、go profile 信息
```
File: app
Build ID: 053ed7dab2cea4aa2ece55e7125b24b2e6c1a958
Type: cpu
Time: Mar 16, 2021 at 9:21am (CST)
Duration: 30.23s, Total samples = 29.46s (97.47%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 24990ms, 84.83% of 29460ms total
Dropped 74 nodes (cum <= 147.30ms)
Showing top 10 nodes out of 28
      flat  flat%   sum%        cum   cum%
   14110ms 47.90% 47.90%    15080ms 51.19%  syscall.Syscall6
    4710ms 15.99% 63.88%     4950ms 16.80%  time.now
    1260ms  4.28% 68.16%     2660ms  9.03%  runtime.mapaccess2
    1190ms  4.04% 72.20%     9050ms 30.72%  github.com/Allenxuxu/gev/eventloop.(*EventLoop).handlerEvent
     770ms  2.61% 74.81%     1680ms  5.70%  github.com/Allenxuxu/gev/connection.(*Connection).HandleEvent
     680ms  2.31% 77.12%     1330ms  4.51%  github.com/Allenxuxu/gev/eventloop.(*EventLoop).doPendingFunc
     630ms  2.14% 79.26%      630ms  2.14%  github.com/Allenxuxu/toolkit/sync/spinlock.(*SpinLock).Lock
     630ms  2.14% 81.40%      690ms  2.34%  runtime.(*itabTableType).find
     510ms  1.73% 83.13%    24690ms 83.81%  github.com/Allenxuxu/gev/poller.(*Poller).Poll
     500ms  1.70% 84.83%      500ms  1.70%  sync.(*entry).load
```

### 二、期望 CPU 随业务量增减
